//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Engine.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Engine.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7H0HeFRF1/+lg9KRqkAEKSIgsEhRIFdQmkgPGhEIbQVpoQqKZJUivUrZgLCUIIROaEpCLgqKskG6dIIgRSmh99z/7t45u3fOziT4ff/n4ex+zPO8L865J8n5ze+cM3Nn5s4oGRRF0V3F/a+75Mzo+r8PWvfo2bdfg359+vTrWzGkXfcBA3v261u3RuWqtSpXrV2thus/qlerUrViSIPBvQcNHtC9bt/ugwcN6Ny7YkjLwV169+z6Xvdhbfv16t637htvVKtWq2r32jW71nzjjTcsVbK4/0oBzy+v3Kh7vz7dBw0YVrn+gO6RmV3ybEOMv/Nc5wFde/Qc0t3SrU+OfpHd+/YdPKDLwMzdOg/q7FbKnj17RreJecspSjXXv7fOZs+ZI5PrP/K4/++LX7IoGR9EZVT6uf7DXR7qGZUXGLQGP/VLqbA4e8Pvjny/f8eeCjXKp65885HreU2mW02xKermf42WyGt1/RX3f7p/WwL7DebfVjTfmo6tnj+YLzFV [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string A1L {
            get {
                return ResourceManager.GetString("A1L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7H0JeBW1F+9Ay6aABWSVpYpQdpELCMoyUIGyyCZFQJYiUkH2VUCWK5siyipLi0ChVLRlkwItUmCQVWkF2UGEolg39l3Ezpvcybk3OTe5xf977yO9n/m+oeTMydzzyy85ySSZRMuhaZppBfKXhPw5rX9e69iv/+AhoUMGDRoyuFpw577DR/QfMrhh3RrP16vxfP1ada3/1K5V8/lqwaGjBo4cNbxvw8F9R40c3ntgteD2o94Y2L9P675jOw0Z0Hdwwzp1atWq93zf+i/0eaFOnTqOmrnIrxRxPbxGi75DBvUdOXxsjabD+w4NtOR5Rtu/81jv4X369R/d1/HmoHxDhvYdPHjU8DdGBL7Ze2RvopQ3b96cxMSgEE2rZf299XPe/PkCrP88Qf45uTxQy3l/Uk7t4PJAF5y/zZzakxRa6NdDrlWJzdt86anVR/Z8V6Vupcw1Lz6w7s+nurU0p6ZP+9jOiaBL1l/yX/K07fQJ7NNKFlrfs8PjxwrtzNSCpuR4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string A1M {
            get {
                return ResourceManager.GetString("A1M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7L0HeFRF9wd86QEBKdIsgHQBaUtTKVdQJAiISFBAMbRQpEmoKmQFgiBd6gaBQAjg0gKhKYFcBARh6aEjBEWKUgKEXu63e++c3TtnZxLe//N9Hyf7OM/zvnHOHZLzm985Z87MnTujZFIURXcXz09PyZ3Z/X8ft+7Rs2+/xv369OnXt3LJtt0GhPfs17d+7SrV61ap/kaN2u7/qFmjWvXKJRsP6j1w0IBu9ft2GzRwQKfelUu2GtS5d88u73cb1qbfF9361q9Vq0aNutW7vVGnS51atWrZqmXz/JWCxi+v8l63fn26DRwwrEqjAd36Z3XLcww2/06uTgO69Og5uJuta5+c/fp369t30IDO4Vm7dhrYydMoKCgos0fFfOUVpYb7Z+pfQblzZnH/x/Oe/5v7YXYl84OIzMpU9394ykM9s/ICg9b4134pFWOCmsw9vuTQ9n0Va1d4svzNR+7n7VjbGopdUT94MbNRyTfP/dOjrue3bWa/wfrbiuVf1fHD55Ly [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string A1R {
            get {
                return ResourceManager.GetString("A1R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7L0HeBXF9/C/dFBAelEpgoBUMZcumAUUCAIiEhRQOpfeOwK50gTpIuVGhEAIYGiB0JRAFhEBuVRDb0GQohBCRwT2f3N3zt2dszPB3+//vg8n93We5/uN5+wknM+cc2ZmZ2dnlXSKoujekvIzpWRP7/2/j1t079G3X/1+ffr061uheKuuAwf16Ne3TrVKb9Wo9FbNoGre/6gSVPmtCsXrD+k9eMjArnX6dh0yeGDH3hWKNx/SqXePzu93HdGyX6+ufetUrRoUVOOtrjWrd65etWpVR+VMKf9KXt8fr9Swa78+XQcPHFGp3sCu/TN69VmGGv/OCx0Hdu7eY2hXR5c+2fr179q375CBnQZl7NJxcMeUSlmzZk2fYmKuMooS5P1592LW7NkyeP/jpZT/KzIyi5L+UVh6Jbf3P1LKP3p6JR9Dq/9Tv+RykVkbfHdi+ZGfD5Sr9sbTVbUee6+fHGHUDVJcilp3ZHqfkKuQ9++lmJvy17axv2D9a4Vzr2334YsJ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string A1S {
            get {
                return ResourceManager.GetString("A1S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7L0HeFTFFzZ+QUBAQHpRgQgKShNYqlKuIAiINAkKCoSSlV4FxB+SlSa9iJQFhIUklNACoSkJXHrbICVUKUEwgLTQi5D77e6ds3vn7EyC3/P/Hk727zyPLnPuye555z3nzNy5c2eUDIqi6K7i/nSXHBld//u8VbfuffrW79u7d98+5YLahA4Y2L1vn9rVKlSqUaFSzcrVXP+oUrlipXJB9Qf1+mbQgNDafUIHfTOgU69yQS0Gde7VvcsnoUNb9+0Z2qd21aqVK9eoFFqzepfqVatWtVTM7P6VfJ4vr/BxaN/eod8MGFqh3oDQfplc8pcHG7+TvdOALt26Dw61dO2drW+/0D59Bg3oPDBT107fdHIrZc2aNaPbxNylFaWy6/Pexaw5sr3k+ser7v/9uSezkvFJWEbluOsf7vKPnlHJz6DV3943uUx41oa/nFxyZOfBMtXeSVnx/lPX9flMt7JiU9TqN4yWyG11/Yr7n+5vi2PfYP62InlWd2j5SkKerSlK [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string A2L {
            get {
                return ResourceManager.GetString("A2L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7L0LnE7FHz9+sHIpWtZdLhGLEB6EXE5ESNpkhYoVntzJrfQNT24lcm3ZZxXLWmrdNotVLMctyW4X9yS2kpSwrkly/mfOmc/zzHyemWf1+//+L7PPv3m9jjWf85l5Pu95z3xmzsycOVoeTdNMK5C/JNyX1/rn+S4DBg4b3mb40KHDh9Wu3K3/yFEDhw9r0bhu/SZ16zdt0Nj6T8MG9erXrtxmzJDRY0b2bzGs/5jRI/sMqV05aszLQwb2far/uK7DB/cf1qJRowYNmtTv3/TRvo82atTIVS8/+ZUIO/O6T/YfPrT/6JHj6rYe2X9EmCUvMNb5ncJ9RvYdMHBsf1e/oYWGj+g/bNiYkS+PCuvXZ3QfolSwYMG8xMTwSE1rYP29+nPB+wrls/5zP/ln9LthWt6bE/NqA94Ns+H8bebVSlBobXYOz66VWLDdh8dWHtj9Va3GNW6vbnbLul+P6jbQPJr+9QSnJMJPWn/Jf0lu6TQHNreyxdb1evbeQ8W239bC [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string A2M {
            get {
                return ResourceManager.GetString("A2M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7L0HeFRF9z9+6aFKb0qRLiICS1PBXEGRICgiQQKKoS0dlFBtWUoQBClSlxoINbRAaEogFwFpG3oHIUgRlB66wP3v3jtn987ZmQS/z+//cLLPO8/zvvGcOyTnM59zzpQ7d0bJoCiK7i6en56SK6P7/z5t0bVb7z4N+/Tq1ad3ldKtOveN6Nand/3aVavXrVr9jRq13f9Rs0a16lVKN+zfs1//vp3r9+7cv1/f9j2rlG7ev0PPbh0/6Dy4ZZ8enXvXr1WrRo261Tu/UadjnVq1atmqZfH8lQLGL6/6fuc+vTr36zu4aoO+nb/M7NZnG2D+nRzt+3bs2m1AZ1unXtn7fNm5d+/+fTtEZO7Uvl97T6WgoKCMHhPzVlSUGu6fd84H5cqeyf0fL3j+78GjICXjo8iMylX3f3jKv3pGpSCD1vC3PjcrxwQ1mnV80cFteyvXrvR02ZuP3c/XsLo1FIeivlAsoyHkne3+6THX89s2sd9g/W3F8q1s93HOw/kSnyp5 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string A2R {
            get {
                return ResourceManager.GetString("A2R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7L0HeBVF98C9dJAivagUQUFAeTGXIgqygiJBQESCYoHQLr1IB4FcqiBIEQPciBAIoYQWCE0JZGnSbmiGjhAEKQoh9CJkv5u7c+7unJ0J/r/n+x5O7uM8z/vGc3YSzm/OOTOzs7OzShZFUXRvSf+ZXvJl9f7fJy27duvdp2GfXr369H61XOvO/fp369O7Xq1qr79R7fU6QbW8/1EjqPrrr5ZrOLDngIH9Otfr3XnggH7te75arsXADj27dfyg89BWfXp07l2vZs2goDde71yndsfaNWvWdFTPkf6vFPH98Wrvd+7Tq/OAfkOrNejXuW92rz7XIOPfeaZ9v45duw3q7OjUK0+fvp179x7Yr0P/7J3aD2ifXil37txZ000sWElRgrw/b5/PnS9PNu9/PJv+f9v75FKyPgzLqmzw/kd6+UfPqhRlaA239UmtEpW70U/HFx/esb9KrVfSlr/5yHs9jNUNUlyK2n9QVp9QsLD376Wbm/7XNrO/YP1rpQqtavtR [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string A2S {
            get {
                return ResourceManager.GetString("A2S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7L0HeBRV98A9oYYqvagUQXoRszQRyAgKBAEjEhSUDkvvTRDIUgVBikjZgBBKKKEFQlMSMkiHDc3QkSJIEQi9Q+bb7NyzO/fsvcH3/3zfk5P9vM/zvvGcmYTzu+ec2+bOHcVPURTdWZJ/Jpfs6Zz/92Xzbt379K3ft3fvvn0qFm/ZZcDA7n371Kle+f2ald//IKC68z+qBlR5v2Lx+oN7DRo8oEudPl0GDxrQoVfF4sGDO/bq3unTLsNa9O3ZpU+datUCAmq+3+WDGp1qVKtWzVIlY/K/ktf1xys37NK3d5dBA4ZVrjegS78MTn3mIca/k7XDgE7dug/pYuncO0vffl369Bk8oOPADJ07DOqQfJO/v3+6ZBNzlVGUAOfPh5f9s2dJ7/yPN5L/LzBbNiXd89B0isX5H8nlhZ5OycfQ6v/e9275Jf4Nfjm1/NiuQ+Wrl01aXeul8/qLrMa9AYpNUS/NTOcSctV0/r1kc5P/Wiz7C+a/Vjj3urafZ0vIHZek [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string A3S {
            get {
                return ResourceManager.GetString("A3S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7L0HXBVH9/+/WGIFQbGgqNhLrFxrIjrGGL2xl8TEgthAYxc0xnrtvcYGRsUSC6CiKGJlNRobWBEVFCG2WKLYo1Hv/967cy67h1l8nuf3PF8O+Wder+fBc3Yhn/ecM7OzZWYkB0mSzJZi/Wkt+bNZ/q9Lx/4DhgxtNnTw4KFDqnl83W+E/4ChQ7zq1ajdoEbthp71LP+o41mrdjWPZiMHBYwc0c9rSL+RASN6Darm0X5k70ED+rTq90PnoQP7DfGqW9fTs0Htfg3r96lft25dQ62c1v9KIdsfr9Gi39DB/QJG/FDjsxH9huWw+HONUv47eXuN6NN/wKh+hr6D8wwd1m/IkJEjevvn6NsroJf1pNy5c2ezSnSuJEmelp/Pb+bOnye75R8FrP/Xqn1uKdubidmkJpZ/WMtf5mySK0drdmRoatX1ub9YdWXThaNnqtar/D7sk7eW47n4uZ6SSWKz6mSzGc6y5adVrvWvHeR/Qf3X3Fy2e3fIF+cS/V5ynuJQ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string B1L {
            get {
                return ResourceManager.GetString("B1L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7J0HXBTH2/gHS8RCs4NEscQWC4I1v4iTEAtWFEtiC6IeauwtGo2eGLuxawSTePZeEbC7GruHFcEulmCNYlcs97+7nedud24Wwu/N+/rgP/P56PE8OwfP93memZ3dnZ0hToQQk7lYPi0lXzbzf+1a9ejZt19gvz59+vWt5NO2+8BBPfv1rVuzSrXaVarV8atp/qG6n2+1Sj6BQ3oPHjKwe92+3YcMHtildyWf4CFhvXt2bdJ9eOt+33XvW7dGDT+/2tW616nVtVaNGjX8fXNa/koB6y+v0rB7vz7dBw8cXuXLgd375zDrcw2V/06eLgO79ug5tLt/tz65+/Xv3rfvkIFhg3J06zK4i6WSs7NzNouJ7uUI8TN/Pr3hnC93dvMPbpb/mid+RLKljc5GvjT/YCmvTdlIQYYWuK9fasUlzg1+O7fi9P7jFWuWf7f2szfm43lYXT+iJ7SfUfaEe4D5r1h+tPy2Xew3KH+bp8eGzi3zJnjseUfcxzqVSm3sNbyI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string B1M {
            get {
                return ResourceManager.GetString("B1M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7L0HeFXF9v89CS1AAqETQAi911BVYBQQDkVpilJDkAQQaQFEQHPoCIhIURIUQgtdSiC0QDYd8YQOITQDSkRApJdQznvO2bNO9qzMTry/9/4fVnzuPM+9Ya09iesz3zWzZ7cZ5sEYszuK86ezeHs6/q9Lx379Bw1uNvjTTwcPqub/Qd9hof0HD2pcv0bthjVqN6pT3/GPunVq1a7m32zEwOEjhvVtPKjviOHDeg+s5t9+RNDA/n3a9P288+BP+g5qXK9enToNa/dt1KBPg3r16gXUyub8rxRw/fEaLfsO/rTv8GGf13h7WN8hWR3+HCP1/06u3sP69Os/sm/Ax5/mHDyk76BBI4YFhWb9uPfw3s5KXl5ens4QfSsyVsfx88FvXt45szj+kdf5f0FXvJhnSpgn+8DxD2d5ZvdkBQVas72D71RZ6vXOj+dWnNx/tEr9Si/Xvv7ccbykqFuHWRnf3tXTZfjecfx0huv8a7vEXzD+Nb9863t2yH06X9xL5jvB [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string B1R {
            get {
                return ResourceManager.GetString("B1R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7L0HWFXH9v89YC8g9kYUa+wFrEmUiSXxWGOJNSqighp7iyYmHLtRo8YW0ahYYsEu9rpj14BdEVFEjcQWG1Ys5z2cPeuwZzEb7u++9/+4yJP1PLm4Zjbc9dnfNbNnl5lhLowxm90SfyZadlf7/7Rr1at3/wH1B/TrN6B/Ba+2PQcP6T2gf50alarWqlS1tncN+z+qeVepWsGr/rC+Q4cN7lmnf89hQwd361vB64th/n17d2/Sc2SbAV/37F+nenVv71pVe9au2b1m9erVfapkSPx/ye3445U+7zmgX8+hg0dWqje458D09vJMw/X/n6zdBnfv1Xt4T58e/bIMGNizf/9hg/2HpO/RbWi3xIMyZ87smhiix4eMedt/Pr2ZOXuWdPZ/5Ej8n0qdsjLXhCBXVtz+j0R7bXNleQRa/QMDHpVblvmzhZdWnj10slyNMu/WfvTGXn+3o36sN7Myfu6Aq8PxGGz/e4nhJv61veIvGP9awZwburTMdj7n/nfMY6xL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string B1S {
            get {
                return ResourceManager.GetString("B1S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7L0HWFTH1/h/QRRQQVQsKCr2EitYYiI6dtfeTTQqNuy9xKiJa9do7A2MiiUWbCiKFb22qHFBRUWwINhbFGMn6v53985Z7j3Mxe/7/vN7PXyfzPMkyzkzu57PnDNz5947RXKQJMlsSdZPa8ruaPlfp7b9+g8ZWn/o4MFDh5T36dhnxMj+Q4f4V69Y5cuKVWr6Vrf8UdW3cpXyPvVHDxo1ekQf/yF9Ro8a0WNQeZ/Wo3sO6t+rWZ8f2g8d2GeIf7Vqvr5fVulTs0avGtWqVfOrnNn6r+S2/XjFxn2GDu4zasQPFeuN6DPMyaJ3HqP8O1l7jOjVr/+YPn69B7sOHdZnyJDRI3qOdOrdY1QPayEXFxdHq4kepSXJ1/L58rZLdtdMlj9yWP/n09NFckyZ6Ch5Wv6wpr/Nlr85Wv1jQ5PLrXNptDJuY8yJ6HLVy3zc+tV7S/71HkpZX8koMUNVR5vgIVs+reZafy2S/4L617xy7ujWJtulnEc+Sh5THIolNy3w [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string B2L {
            get {
                return ResourceManager.GetString("B2L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7J0HXBTHF/gXG1gQEBtCFHuJFaxJ1FFjQY1iT6yAemDvRhOjJ8YSe6ycGjlLLGBBsSu6lqjRw4IICmpAI9afYlcs97+7nXe3O8yC/P75/3j4z3w+yfHezp3v+96b2dnd2RnBThAEo6mYP82lUC7T/3p0Dho0fESLEcOGjRhe3bP7wNFjBo0Y3rh+zToNa9Zp5FXf9Eddr9p1qnu2GDd07LjRAxsPHzhu7Gj/odU9fccFDB3Uv93AiV1HDBk4vHG9el5eDesMbNSgf4N69ep5185r/ldcLT9es/XAEcMGjh09sWbz0QNH5jHp7cdL/04B/9H9gwaNH+g9YFj+ESMHDh8+bnTAmDwD/Mf6mys5ODjkMpvoXFkQvEyfz285FMqf2/SHk/l/41/kE3KlTcklDDb9YS5vjbmEohStxbERqdXWObT67crGmBPnqtWv8mHLF+9Mx71oXS9BK5DU85InnFuY/hXzn+Zfi6K/IP81N5ftfTsVjHU58kFwnmZXLrVt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string B2M {
            get {
                return ResourceManager.GetString("B2M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7L0HXBVH9/8/YEMFe9co1qixY00sk1hvLLHGqFERFdRoLKixRa7dGGM3EU0UjZLYYkGxy9pLwIINrGAhtkTsiuX+770757JzmIXn+/0/v5eHvL7n9XoePGcXct77OTM7W2aWuTHGbHZz/HSYp7v9/zq379f/68GNBw8aNPjrSt6f9x0W2H/w1w1qV6let0r1ejVq2/9Rs0a16pW8G48YOHzEsL4Nvu47YviwXgMrebcd4Tewf++WfUd3HPxV368b1KpVo0bd6n3r1eldp1atWj7VMjn+K3mdf7xK876DB/UdPmx0lU+G9R2S0R7PMlL/72TrNax3v/4j+/r0GZR18JC+X389YphfYMY+vYb3cuzk4eHh7kgx1/uM1bD/fHLDwzNrBvs/cjr+L8NDD+aeFOTOnid6OHFe2dxZPoHWeP/gxIq/ejT7Jea36IMnKtYu/3bdh6/t2yPEvjWYlfF1XdydTq4H9p+OdB1/bY/4C8a/Vjj3hh7tsp/NHfGW5Zrk [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string B2R {
            get {
                return ResourceManager.GetString("B2R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7J0HWFXH1vcH7AqKNRai2HsDjZqoTCzRY4stGjUoNtTE3qKJCceu0agxakSjYo/YxV537JoDdgULgkassWHFcr7D2bMOexaz8f3e736Pizx3PU8urtkb7v+3/2tm99nMjTFmd0TSz6TwcHf8T/vWvfv0H1B/QL9+A/pX8GnXc/CQPgP61/moUtWalarW8v3I8Y9qvlWqVvCpP6zv0GGDe9bp33PY0MFd+1bwaTmsW98+3Zv2HNl2wDc9+9epXt3Xt2bVnrVqdK9RvXp1vyoZkv5fcjv/eKVGPQf06zl08MhK9Qb3HJje0Z5puP7/k7Xr4O69+wzv6dejX5YBA3v27z9scLch6Xt0Hdo1aaXMmTO7J0n0Ks2Yr+Pnk+uZPbKkc/wjR9L/BPbLytwTg91ZW8c/kuKV3Z3lEWj19w94WG5p5s8WRK08fTCy3Edl3q75+LVjubdY15dZGT+9192ZePVz/L0kuUl/bY/4C8a/ViDn+s6tsp3Nue8t8xrrVuxh [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string B2S {
            get {
                return ResourceManager.GetString("B2S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7L0HWBVH2/8/2Asg1tjFGnsBa2IZuyf2EjUaFRuWGLtGExOO3ahRY9QIJoolFtRYsNeNXXPAXrCiRjRqFMWKZf+Hs3Mfdm5m8f29/+e9vHmuzHU9D96zC/l+9nvP7GybYR6MMd1ZEn4mFM9Uzv/r0KZvv4GD6g/68stBA8v6tu89dFi/QQNrVS1fqXr5SjX8qjr/UdmvYqWyvvVHDBg+YmjvWgN7jxg+tPuAsr6tRvQY0K9n096j2w36ovfAWlWq+PlVr9S7RrWe1apUqeJfMW3CfyW764+Xb9x70Je9hw8dXb7e0N6D0zjr0480/juZug/t2bffyN7+vb7MOGhw74EDRwztMSxNr+7DuyfslCFDhlQJEn0+ZMzP+fPJzQyeGVM7/5El4f+uhmdiqeKDUrFTzn8klFd6KpZDoNXfNyi29NIMjX69sOLUgcjSVUu+XfPRa+f2ELGvH7MzHnsilSvwGe/8ewlyE/7abvEXzH8tT9Z1XVtnPpN171vnvh5F [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string B3 {
            get {
                return ResourceManager.GetString("B3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7L0HVBTLFrZdJANijgjmnFEwYCwwjglzQOUYcMCEOStJMGEWAxhARYwoCgoqoRsMqKCgoqiImNEjioqS1Pm6md6cqZrGc+93/7Us//XVWp46b3UD7zN7V3WY7iqkgxBSCUWsxWKkK/xn9DDHaU6ze86eNWu2U8u6o6bOmz9ttlO3Dq3bdmrd1rJdB+F/LNqZtW1Zt+fCmQsWzpvazWnqwgXzJs1sWXfIwskzp00ZMHXpiNkzpjp1a9++XbtObadadpzSsX379uZmBuJfqVz4y1v3nTp71tQF85a2tp43dY6+0F5ykfrvGE6aN8Vx2qKp5vazSs+eM9XJaeG8yfP17SctmCTuVKpUKV3RYoUmCLUT6uwXpYxK6wn/U178T9K7kkg330UXXRH+RywFKl1URULrGTM7q/mhUn32pRy5c/lW8w5Nf57s/F3YvlHatx1yRdiklW6hqLBeqEW74m+LlH6D5m8zrnjabmiZexWjf6IKq3TqZ/WvubS6+Ns8pe0V [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string C1L {
            get {
                return ResourceManager.GetString("C1L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3J0HWBRJt/cLBEXMOeecCeZYmMeMOa9xwARizgKiYkbEACZMGFGUqKJ0Y0IFBUUERcWMrgEjSemve6YPO1XTg/ve997H8jvP49b+qxo4vz6nqnMVMkIICaJJpWSFjcX/DBtoP8XBsYvjjBmODo2rD508a/YUR4cOLZtatm5q2caqpfg/za0sLBtX7zJ3+py5syZ3cJg8d86s8dMbVx8wd8L0KRN7T1442HHaZIcOLVpYWbW2nNym1cRWLVq0sLYwlf5KKc0vb9pjsuOMyXNmLWzaedbkmSZifYF52r9jPn7WRPsp8yZbT5pR0HHmZAeHubMmzDaZNH7OeGkjMzMzY8nF4vUQshLLr8/NChfMJ/5PMek/1Y/kR8ZZy41RafF/JMsWxP+X0bpEOqY1PGDWfXfi4TuXbzVsWT/nRNsfYnvyYe22VsgZ4aR47Z4oXl38K9L/Sr/tgvwbdH9bhRKnxtoWii8RkYOKrzCqmdar4sJy0m9bKbcXN5b/x1j+R1pa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string C1M {
            get {
                return ResourceManager.GetString("C1M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3L0HVBRJG7ZdJEXMOYA5h1WSYqZQVx0T5ryuAQdERTFnSSqKATECKhgxoKKAooJ2m0VQUUCSiBlzlqDSfzXTDztd0+z3vt97/mP51Tlu7V3VwH3N81R1nGqkhxASSBFrsZTRJ/8ZMdhpisuM7jOmT5/h0qre8MmzZk+Z4dKlXWuL9q0tOli2I/9jbWlu0ape97nT5sydNbmLy+S5c2ZNmNaq3sC5E6dNmdR38sKhM6ZOdunStq2lZXuLyR1sJtm0bdvWytxI/CuVC395616TZ0yfPGfWwtbdZk2eaUjaS87T/B2TCbMmOU2ZN9nKYXqpGTMnu7jMnTVxtqHDhDkTxI2MjY31RYsVmiJkSeovT4zLlDIg/1Ne/E9qC2Okn79cH8WT/xHLd0EfVZHQul+c8aHFXuOeO1NC7l6+1aJds4LQjj9I/xZpW0vkhnAprF8oKgSTWrQr/rYY6Tdo/7aaFY+PG1Q6seKFAlTBU6/Bhz61FlYXf9sKqb+CvvQ/+tI/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string C1R {
            get {
                return ResourceManager.GetString("C1R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7J13VBTL1vaLZEAxZzGjmI6SDBgL9ahjwpzFhCNmwYSRaAQTYgADqAgmFAUVFaRbDKhgBAVFxIweMaLAqMzXPdMbp2rau9773j9u+a6v1jqnfLp6huc3e1d1rkYGCCG1UMRaLGUNhf+NGOwybfac7nNmzZozu2X94VPc5k2bM7tz21bW7VtZ29u0Ff5hZ2Nl3bJ+9wUz5y9wm9J59pQF890mzmxZf+CCSTOnTe47ZfHQOTOmzO7cpo2NTXvrKfbtJrdr06aNrZWJ+Fcqa768Va8pc2ZNme+2uFU3tylzjYXlJRdq/47pRLfJLtMWTrF1nlV6ztwps2cvcJs0z9h54vyJ4kqlSpUyFC1WsETIRqjznpcqW9pI+Ed58X/czNLIUOVhiGKEf4jlu9oQVZHQul+c87H5/lI9d6dH3L10s3nbpkVHO/wQ2pdJ69ogT4T77jDUiAqmwveJdsVvi5e+QffbalY87jSoTGrFhCJUwceg4cc+tRZXF79tpdRewVD6 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string C1S {
            get {
                return ResourceManager.GetString("C1S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3L0HWBRJ27ZdJEVEMUfMac0oGBBDoS465hxQWQMOmHNYAwzJiAkxgAkFMYIoKKiA3QRBBBUlmRAzuqKoKEFhvu6Zvtnpmma/9/me/z+2fOs43Nqrq4HrnPuu6jDdVUgHIaTkCl/zxViX+8/kcY7zFi8ZtGTRoiWLOzWfNHf5inlLFvfr2aVb7y7dLLv35P7HortZt07NB61auHLV8rn9Fs9dtXL5rIWdmo9ZNXvhvDnD5/45YcmCuYv79ejRvXvvbnMte83p1aNHD3MzA/6v1Fb98i5D5i5ZNHfl8j+7DFw+d6k+t73yavXfMZq1fI7jvNVzze0XVVmydO7ixauWz16hbz9r5Sx+J0NDQ13eYo12CHXn6oKXhsZV9Lj/MeH/4zOlEtItcdZFO7j/4csPpS6qI6ANilmS38Hf0OZI1qn7cXc69Pyt7Hyfn1z7RGHf7kiB8JYhuipR4xxX83b53xYl/AbN39aw5gW7sVXTat4oQzXcdFrmD2v0Z33+t3kI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string C2L {
            get {
                return ResourceManager.GetString("C2L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3L0HVBTLFrZdIBgwZxRzTkdBwBwK8xgxB5SDacAEipgViSaMiAFMKCoqYiCriN0ERQRBJamImDGgGAmK83fP9OZM1zSee7/7f8vyq7U8dd6qBt5n9q7qMN1dSAshpOAKX/Olijb3n8njbObZ2g20W7TIzrZTs0lz7ZfOs7Pt262zUY/ORj27duP+x6SroVGnZgOXLXRYZj+3r+3cZQ72Mxd2ama+bNbCebNHzF01wW7BXNu+pqZdu/Ywmtuz++zupqamxoa6/F+prfzlnYfOtVs018F+VecB9nMX63DtFZar/o7eTPvZNvOWzzWes6iS3eK5trbL7Gct1Zkz02Emv1HFihW1eYs12iLUlau/PKtYpVI57n+q8//x8NdF2sXrtdF67n/48l2hjeoIaAOj7fI7+FUccijT/27s7Q7d2v082+sH1z9U2LYrckI4q6K2UtT4m6t5u/xvuyr8BvXf1qDmecuxlVNrXvuJarhqtcgf3nBVff63uQv9NbSF/9EW [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string C2M {
            get {
                return ResourceManager.GetString("C2M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3L0JXA3fH/9/2khZs5N9pw9tlC0n2a5932XLtUfJTpIQQhIpWxTZIipCmKmQNqKSSrJnz9pC3f/MvfPuc+fc8X18v//P7/f4HL/zePicz2vOVK/nfb/PmTNzZ+YgLYSQgit8zZfK2tx/xo2cM9dxkd2ihQsXOZo0HTvLecncRY49u3Q0s+5o1tW8C/c/luamZiZN7ZYucFnqPKun46ylLs7TF5g0Hb50xoK5MwfNWjl60fxZjj07dzY3tzab1dVqplXnzp0tTPX4v1JT+cs79p+1aOEsF+eVHXs7z1qsy22vuEz1dwymO8+cM3fZLAuHhZUWLZ7l6LjUecYSXYfpLtP5nfT19bV5i9XbIGTO1d+e61eupMP9TzX+P6e2VkDaJeu00SHuf/jyU6GNaglodjGLCtoH6fc7mBlyPy6lfZe2ZWe6/eLa5cK+5sgN4S4TtZWiOsvVvF3+t10TfoP6b6tf45z9CMO0GjfKUPUNWs0LBjZYWZf/bRuF9urawv9o [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string C2R {
            get {
                return ResourceManager.GetString("C2R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1H13VBTL9nWRDCDmLOacJaiYC/WqY8KcxYQjJhTMmWQEE2IAAygIJhQFFRV1GgyooKKAqIiY0StGFAaV+aqZPtypmvat9/vuH688a2G5u5ph79mnqlN1FTJACGlIiKUYpQzJPyOHOE13ntNjzuzZc5xb1Bkx1XXe9DnOXdq1srRtZdnBqh35j41VG8sWdXosmDV/gevULs5TF8x3nTSrRZ1BCybPmj6l39Qlw+bMnOrcpW1bKytby6kd2k9p37ZtW+s2JuJfqVD44a16T50ze+p81yWturtOnWtMthdfqP07ppNcpzhNXzjV2nF2yTlzpzo7L3CdPM/YcdL8SeJOJUqUMBQplm2MkBUpc16UKFXSiPynjPiPd4/iyDB/lSFaRf4jxg+NIaooSesRO+dTs+ASvfamhd27crtZuyYFxzr+JPW9pX2tkBvCoXsNC0HZcuTzRLrip12UPkH306qVO+Ew2Cy53OUCVNbToN6nvtWXVBE/bbVUX9ZQ+o+h9EPH [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string C2S {
            get {
                return ResourceManager.GetString("C2S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3J13VBTL9raLpIhizmLO4SjJiKFQjzomzFlMOGBCwRyJRjAhBjCAimBCUVBRQafFgApGQBRFzOgRRUUJKvNVM71xqqa96/7W+eOW317rnPLtauB9Zu+q6e7pqUZ6CCE1CbEVo4w++d/IIU7TnGf3mD1r1mznVvVGTHWdO222c5d2rS06tLboaNmO/MPa0tyiVb0e82fOm+86tYvz1PnzXCfNbFVv0PzJM6dN6Td18bDZM6Y6d2nb1tKyg8XUju2ntG/btq2VuZH4VyoV/fLWvafOnjV1nuvi1t1dp84xJNtLLtD8HZNJrlOcpi2YauUwq9TsOVOdnee7Tp5r6DBp3iRxJ2NjY33RYvmmCFmSNueFcZlSBuQf5cT/fWhljPQL3PTRc/IPMb6r9VFlCa3HpdnZLfYb99qdGnbv8q0W7ZoVHu30g/Qflva1RO4If3ylXyTKK8nvE+2Kvy1W+g3av61GheP2g0snVbhYiMp76TXI7ltzcTXxt62U+svrS//Q [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string C3S {
            get {
                return ResourceManager.GetString("C3S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7L0HVBRJ1/g9BHPCLKZFMIsRsyJlFrNizhEx51HXNOaEigQVRAUUAyoiCIKJVjBjzpld05oxrrKr802oO91V080873P+3/HCeeqc3fbebuD+6t5K3RVUViqVSqtL+qs+5bXW/a93d6/REya2nDh+/MQJzg69Rk6ZOnriBNf6NWo3rFG7UZ36un/UrVOrtrNDy+njpk2fMtJ1wsjp06YMHefs0HX6sHGjh3cYOavHxLEjJ7jWq1enTsPaIxs1GN6gXr16LrWy6f9KYcMvr9F25MTxI6dNmVWjxZSRk2x1+hxq49/JPXTKcK/R6pEuI8bnmjhp5IQJ06cMm2o7Yui0ofqHcubMaa030a6SSlVHd/38JGfeXDa6fxTQ/+/QvOwq6/T51qo9un/o0z9aa1URitby5MS0qttyttl8Z+e15EtV61f+ubfxv7r7U+mzdVQaFSlX29og2MXrrnpz9b/tGP0N0t9mX3D/oG55bhRM/KmyW2TlmNa+5Kzi+t+2hN63 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string D1L {
            get {
                return ResourceManager.GetString("D1L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7H0HVBRZE24TzDmgYlrWHFgTZkV6jZgD5oiBpJh11FVxzAkVMQ4iDirmgKAYUGkVjGAOa8Y158waVudNuDXdXdOX+f//vXe4zNl7zu5Y1XeG+uqrm0NzdhzH6fTJ8GlIue31/+vRxT9gxMhmI4cPHznC1aW7z5ixASNHuNetVrN+tZoNatXV/6N2rRo1XV2ajQ8cN36Mj/sIn/HjxgwMdHXpNH5QYMDgtj6Tuo4c5jPCvU6dWrXq1/RpUG9wvTp16rjVyGL4K4WMP16tlc/I4T7jxkyq1nSMzyhHvT6byvR3cg4cM9g/QOXjNmR4jpGjfEaMGD9m0FjHIQPHDTRkyp49u73BxPwVOa6W/vPTw+y5czjo/5HP8L8zs7Jw9t+m2XNH9P8wpO86e64wgdbs+Mh3VTZkb7n2z82XE89XqVvp546G/+ifzyZ5a3Fqju91z+SJ/J30f8XwT+OvkV+Q/ppzgd39O+e6WiDhJ5d/pl2Zd22KTypq/DXyPL89+Yc9 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string D1M {
            get {
                return ResourceManager.GetString("D1M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3J0HWBRJ8OiXYMIcOLNiuvMUFcWsSJ8R8xkwB9QzZ9E1nbLmhIoJBVEXFQMqoihmHXPCnDOeOWfPzGN3u3ama2fc+//fex8F/X13a9XMLvXrqs7dMzoHnU6XkJhMn6aUwTHxf62b9+o9YGCtgf37Dxzg7taq+xD/3gMHeFUsXbZy6bJVylVM/Ef5ch5l3d1qDes3dNiQ7l4Dug8bOqRLP3e3P4d17de7W8PuI1sO7Nt9gFeFCuXKVS7bvUqlbpUqVKjg6ZHK9Feym3+8dL3uA/t3HzpkZOmaQ7oPck7Up9Fb/o5LlyHdevXWd/f8q3+6gYO6DxgwbEhXf+e/ugztYropbdq0jiYTs/ym05VL/Hx/L22GdE6J/8hs+t+H16l1jl8CHHVPEv9hSl8THHU5OFqtAwNfl1iRtu6Sq6vPHzpdomLxH+urfku8vonfW05n0LFzrR3NQpbHiZ8mc02/9p3/gvLXcmfd2KlZ+otZ9/3QZZngUPh1gzwjc5p+7TC/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string D1R {
            get {
                return ResourceManager.GetString("D1R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7J0HVBRZ0KiHYAATopgDYlzFiDnR6+qas5gDJsxZMa06mAMqiqggCqgYQBBFUUy02VUUcw64ZsUcVjHMm3Brum9Nt+z7z3vHgvPfc3bHqu4Z6rtVN9++rbHSaDQ6fTJ8GlJ2a/3/unQYPGTkqD9GjRgxaqSrc+eBY8cNGTWyQc1KVWtXqlqnWk39P6pXq1LV1fmPCcPHTxg7sMHIgRPGj+073NW53YR+w4f0bzlwcqdRwwaObFCjRrVqtasOrFOrf60aNWq4Vclk+Ct5jD9eqenAUSMGjh87uVKjsQNH2+r1WbxNf8e+79j+g4d4D3QbMMJu1OiBI0dOGNtvnO2AvuP7Gm7KmjWrtcFEh7IaTTX954cHWbPb2ej/kcvwvwfPs2isU2dYa67p/2FIX3XWmrwM7Y8jo96U35D1z7XXN188dq58zXI/ttX9pr8ewu6tptFqhMAIa6Pg0E7/ewZzDb/2nf2C/NcK5t7eu322y7kTfmgcZlm5vGlRaHJ+w68d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string D1S {
            get {
                return ResourceManager.GetString("D1S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3L0HVBTZE/A7BANGFBOuOWdRVDAgraurmBUxr2vEnHVMK445oaKICqKCiFkcQTCg0opZUMyirjlHxIxhHjNza7q7ptv5v+9771Bwz9ltq7qB+t2qm7pvUFmpVCpdetJf9SmPdfr/uncZOmz0mD/HjBo1ZnSNMt0Gj58wbMxotwa16rjWqtOwboP0f9Sr61SnRpk/J42cOGn8YLfRgydNHN9/ZI0ynSYNGDlsYNvBU7uOGTF4tFv9+nXrutYZ3NBloEv9+vWdnbLp/4qD4ZfXajV4zKjBE8dPrdV8/OCxtun6HGrj38nVf/zAocPUg50HjbIbM3bw6NGTxg+YYDuo/8T++ody5sxprTfRvrJKVTf9+vFRzjx2Nun/yK//X8ll2VXWaTOtVQXS/6FP33XWqkIM7c/jY1KqheX8a/3NrZdPXKjWoMqvXY1+pN9PXmp8tq5Ko+IWuVobBHs+/ao3V//bfrLfIP5tjgX29O2c+2qBuF8q+zlW5VLaFJ9aVP/b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string D2L {
            get {
                return ResourceManager.GetString("D2L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7L0HVBRJ1z4+BF0wYhbXnLMoZmWpNWIOmFBXMYDoGjCNuibMWTHiIEoSXVFxBDMqrWAGxZwV85oxrnn+E+pOd9d0Me/3/b/f8cJ565zd9t4u4D73uZW6kspGpVLp9MnwNKRctvr/9ezqN3TkqOajRowYNbJ66R4+Y8YOHTXSrX7N2g1r1m5Up77+H3XruNSuXrr5+OHjxo/xcRvpM37cmAHDq5fuPH7g8KGD2vlM6jbqT5+RbvXq1anTsLZPowaDGtSrV8/VJZvhrxQw/vKarX1GjfAZN2ZSzWZjfPzt9fpf1Ka/k2PAmEF+Q9U+roNHOI7y9xk5cvyYgWPtBw8YN8CQycHBwdZgolMllaqO/vn+gUMuRzv9P/Ia/ncnPJvK9st0W9UF/T8M6avOVlWQQmt+dFR61UiHVuuvbb6QdLZq/co/tjX+pn8fTPPWUQWoSN7nJk849dP/FcM/Db/tO/0N0t/mnG9Hvy45L+VL+KFymmVTNr1tsUlFDL/tGH3v [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string D2M {
            get {
                return ResourceManager.GetString("D2M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3L0HWBRJ0PC/BBPmgIqiYk6oKGZFxnRizoo5Yg4IuqZTUDGjIkYQFVDMIoLxDIw5oWIW9RRzVoxn5tvQtTNdO+O+//f/fY8F/Tx3a9XMLvXrqu7pPBorjUaTqkv6T33KZq37X9cOQ4aOGt149MiRo0c5O3Xx8vEdOnqUW83KVWtXrlqnWk3dP6pXc6nq7NR43Iix43y83EZ5jRvr02+Es1O7cf1HDB3Q0mtip9HDvUa51ahRrVrtql51ag2oVaNGDVeXDPq/ktfw45WbeY0e6TXWZ2LlRj5e3rY6fSat8e/Y9fMZMGSo1st14Mgso729Ro0a59Pf13Zgv7H99DdlzpzZWm9irrIaTTXd58eHmbNlsdH9I6f+fy2tMmmsv/lZa9x1/9Cn76nWmnwMrfHR0SkV1mX+a/XNjZePX6hQs9yvbXV/6K5nYvdW0/hrhK+9rQ1CrhTdp95c/a/9ZL8g/zWH3Dt6t896NXf8L02uGVYlUloUmlhA/2sn2PVc1uwf [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string D2R {
            get {
                return ResourceManager.GetString("D2R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3L0HWBRJ0PC/AiZMqKCiqJg9RUVRMTuHcoI55zNgzoqK6dTFHDCBqCBKUERFEURQD5Uxc4o5Z8w558if3e3ama6dkfd7v+//UNDPc7dUzexav67q3DOtyabRaFLTku5Tl/Kapf2vW8ehw0aPaTZm1Kgxox3suw7yHD9szOjGdavXrFe9Zv1addP+qF3LsaaDfbOJIydM9BzUePSgiRM8+490sG8/0WPksAGtBk3pPGbEoNGN69SpVatezUH1nQc416lTx8kxu+5fKaz/8eotBo0ZNWiC55TqLp6Dxlqk6XN6Gf4dy/6eA4YO8xrkNHBU7jFjB40ePdHTY7zFwP4T+utuypUrl5nORKtKGk2ttM8P93PlzW2e9kcB3f+uvsypMfs200yTnPaHLn1PNdNYM7Rmh8a8qbIh11/rrkacP3K6St3Kv7Y1+JF2fSW7t5ZGqxHGbzPTC1Yd035PZ67u136yX5D/mm3BHX065LlYMPGXxmp2trJvWhafUlT3a0fZ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string D2S {
            get {
                return ResourceManager.GetString("D2S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7L0HVBTLt/bdIGbFnBPmhBGzomXOAXMOqASzmCODWTErShIQBRUMCCigIiUiJsSEqCiGo2LOWYH5Znpqz3TXNNx7/+/9ltuzbq11Trurmp7n13tX6O7qasFEEAS1Jmm32lTAVPO/If0dHKdN7zh96tTp0ywtBk90muU4fZp1s/qNWtRv1LJxM80/mjRu2MjSouOcKbPnOE20njZxzmyncVMsLfrNsZ3iOL7nxAUDp0+eOM26adPGjVs0mtiy+fjmTZs2tWqYU/srxcSD1+86cfrUibOdFtTv4DRxhpkmP/dc3e/kG+c03sFx7kSrCVPzTp8xcdq0OU62s8wmjJs9TrtTnjx5TLUSC9cUhMaa7ZcneQrkzaH5RyHt/+Jt8wimv5xNhROaf2jTb7WpUJyhdYyd/qHOnjxddt3ZdyMusU6zWpkHW6VrypexfRsLKoFc8TEVjcJNNMfTytUeLZodQXq0MkWOjLbJn1QkJlMovNykyoceZReU0h5tJSsvbMr+ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string D31L {
            get {
                return ResourceManager.GetString("D31L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7L0HVBRJ1/jdBHPOWTG76qqAAQNa5hwwZ8UAmBUVswxizgGVpCAqIiYEVFDBEhHTiAkxYlgFc84KzDeh7kx3TQ/7vM/7/g9Xz1fn7Ja3qpi+v7q3QldXVwtmgiCo1EETa0J+c/X/BvR2GTd5StspkyZNmVzXqv9Y1+njpky2b1zP2q6edVObxup/NLRpYF3Xqu3MiTNmuo61nzx25gxXx4l1rXrNHDVx3OiuY+f0nTJh7GT7Ro1sbOysxzZtMrpJo0aNbBvk0FylmPbH63UcO2XS2Bmuc+q1cR071VKdnstNd528jq6jXca5jbUdMynPlKljJ0+e6TpquuUYxxmOmkK5c+c216hYuKYg2Kjjz09y589jof5HIc3/SlgUEMx/upsLedT/0IRfKnOhOENrGzflfe2duTtsu73nenxi7ca1Mvc3S1fnXzPXlbURFAJp391cKxRWqmONuppfi2G/IP61MkUODXfIl1TkVKZQ2NOsyvsuZeeU0vzaEpZf2Jz9 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string D31M {
            get {
                return ResourceManager.GetString("D31M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3L0HWBRJ1789IOacw5rzGgkGVkXLLIo55wzmgIp5GRRMmEUFRAEDKiaSCsYyYhgRFcWEYc05Z2G+CXVmus80PM/7/t/v8rh1XbvtqWp6fnefU6Gru7pVViqVSqtL+q0+5bLW/a9nlxEjx41vPn7s2PHjapTtMdx90sjx45zq1bJzrGX3l3093T/q2Nva1SjbfMqYyVPchzuNGz5lsvvgMTXKdpoyZMzIoe2GT+82fvTwcU5169rbO9oN/6v+0Pp169Z1sM2s/5WChoPXaj18/Njhk92n12rmPnyCjS4/q4fxd3IMdh86YqTHcIdhY7OPnzB83Lgp7kMm2QwbPHmwfqds2bJZ6yXmq6JS2eu2Hx9ky5U9k+4fefX/WzM4u8r6u6e1apHuH/r0Q2utKiTQmh8f/7bapmyt1l/fevlkQrV6VdN2NvipK+8i9rVXqVVs7Etrg5HPT3c8vVz90Q6LI0iPVjz/ngGdcyblP5qmyjfXqvzbtiWmF9UfzUeU57MW [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string D31R {
            get {
                return ResourceManager.GetString("D31R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7J0FWBTf9/8XRMXuLuxWYLFrbFEM7G5BbLEDWRQTG1AWULBQsVBQwbx2LVjYYnzswA4M2P/GPbszZwe+v/g/j8fP87vP8/mMZ+6w+37tOTfnzh2FlUKh0OqS/qhPOa11/+vVdaTHuPEtx48dO35cDbueIzwneYwf16RuLYf6tRwaONbV/cPJ0d6hhl3LKWMmT/Ec0WTciCmTPYeMqWHXZcrQMR7DOoyY0X386BHjmtSp4+hY32FEg3rD6tWpU0dpn1n/LQUMH16r7YjxY0dM9pxRq4XniAk2uvNZpxq/J/sQz2EjPaaOUA4fm238hBHjxk3xHDrJZviQyUP0F9na2lrrJeatrFA46o5fntjmzJZJ9488+v+53MivsP7pba0QdP/Qp19aa0VBjtby5PgP1TbZtll3e+u10wnV6lZJ29nwty7fll/rqFAphDpNMxmMvL91R71c/acd5Z8g/rRi+fYMdM2RmO94miLvPKtyH9oXn1FE/2nzeX5ea/4Pa/6f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string D31S {
            get {
                return ResourceManager.GetString("D31S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7L0HWBRJ18c7AiYwoIgKJsyYUcyJWpVVzDkHxIRrQFEx62AOqAgYQFRAMIAiimJApVQMq5izroorijnnxGVm6kx31XT7vt/9vns97LP1PLvjqe4Z/r8+51ToUK3JptFoMjKL7lNX8phl/q9HZ8/ho72ae40a5TW6qkP3Id7jhnuNblK3es361Ws2qFU38x+1aznVrOrQfMLI8RO8hzQZPWTCeO+BI6s6dJzgMXL4oDZDJnf1GjFkdJM6dWrVql9zSIN6g+rVqVPH2Sm77q/Y6H+8esshXqOGjPeeXL2Z95AxFpn1OX0Mf8dyoPcgz+E+Q5wHj8rtNWbI6NETvD3GWQweOH6gbqdcuXKZ6SRaV9RoamV+vrufK09u88x/5Nf9b/CFXBqzLzPNND0z/6ErXzPMNIUYWvMjXq8qb8j1+9rrmy4mn61c1/HH1obfMrc7sH1rabQa4vnKTG9Yb8j8PZ1c3a8dZL8g/zW7Atv7d7K6XCDph8Z6drYyr1rbTy6i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string D3S {
            get {
                return ResourceManager.GetString("D3S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7L0HnBRFEzY+ZAQEBEkSPAFJnoRbMiINKEGicCQRONKSBUGUINxKVNKRYQ8OjigcSDokhyEIinsgQQlKUslZcrib/85O1+xMzfSe7/u935+6/ejfD9euqd2rp5/q6jjdUipJkhRvUj/VlCW19z+tmnXv8Unf2n379On7SWhIy679B/To+0n1iqXLVS5drkpYRe//lA8rWy40pPbA3p8N7N+1+iddB37Wv2Pv0JCmAzv17tG5QdfB4X17df2keoUKYWGVy3WtUqlzpQoVKjjKplP/Sk7fj5eu27Vvn66f9R9culb/rv3SeuUZPtf+TqaO/Tt37/F5V0eXPi/17df1k08G9u80IG2Xjp91VJUyZsyYWjUxe3FJCvN+3vsrY5aX0nj/J5v6n+zDX5JSP4lMLaX1/o+aniqppVc5tNq7+94utShjnZgT3x7Ze7BUxRJJK6s+8z73DNN0wySXxCpc1koi+8fev6L+r/pr2/kvGH8t3yur23+Y+dgrO5Ok7CNT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string E1L {
            get {
                return ResourceManager.GetString("E1L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7H0HfBVV0O+G0EWaIkVKKCIdzEUUBLJ0UJoQFFQgtNBBOkjJld4UEBACBBJAQFB6R2CRppjQlaIgWBBEEKSDyX07u2d2z87dc2P8vvc4yXN/v0s4s3Nm5z9zelWCFEXx6Q/8hSdbOv2fN1t0696nb52+vXv37VMu5I0u/Qd079unRpUKL7xc4YWqoVX0/1QOrfRCuZA6g3oNHNS/S40+XQYN7N+hV7mQ5oM69ure6bUuw8L79uzSp8aLL4aGvvxCl6ovdXrpxRdf9FTKAF95yhBeoUGXvr27DOw/rELt/l3eTa/TMw02v5O1Q/9O3boP7uLp3DtL33e79OkzqH/HAek7dxjYAZgyZ86cDlTM+byihOp/b/+cOVuWYP0/OeCfd6dnVNI9jEqndNb/A88jXzrlaQatzpd9b5RZkrl+zOnlx/cdLlOlVNJn1f7W35djvKGKV1ELtTQtkXOp/hf+C9J2Mgm8tPy51rR7/YmTuXYnKTnHBBW78WqBYXlB2jj2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string E1M {
            get {
                return ResourceManager.GetString("E1M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7H0JnE/l9/81QyZkK6EQWkjW+YS0zUW2knwzihbGNmRJSKiYT5ZICiHGOpYQFWUvyxUpmiFRoW9Fi0JEKSHz+d9z7zn3Pvd87nPHp//v9++Z+fe8Xh/jOfecc8/7Oc++XS2fpmkRM8BfCEXizH8evL/HY4/3bdy3T5++j1ev+EC3/gMe6/v4HfVq1rmlZp0GifXM/9ycWLtO9YqNB/Z+cmD/bnc83m3gk/079a5esfXAzr0f63JPtyHJfXt1e/yOunUTE2+p061B/S7169atG6pdAN5yuaW8ZrNufft0e7L/kJqN+nd7Ir9JL/iU/Z5Cnfp36fHYU91CXftc2veJbo8/PrB/5wH5u3Z6shMwJSQkxIGJxatoWqL59/R3CUUujTf/Uwz+eXXVJVrcubQ4baz5HwjnI3HaFQit8ft9T1abn9B01r5Fn27dWa1e1ew3bv3LfH4/8iZqYU1v0s5OieJvmH/hv6BtA2oQtZUtsazDfwrvLbEpWys+Il/lk3df [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string E1R {
            get {
                return ResourceManager.GetString("E1R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7H0HmBRF0PZwRzgBEVQkKEFQEBWBW5IBGUAElKQcShA40oIEQRAFUW4lGpAcXOIRJUmWYIAhqrBHVsDEIYoEQREESTf/hK7Z7truPf3+73+o2995nhG7pvq23n6rq3u6e7q1bJqmmdZl/2tfeeOs/zz/bNcXX+pVp1fPnr1eerDkc5379H2x10s1qj5UqfpDlR5OrGr9T+XEipUeLFmnX49X+vXpXOOlzv1e6dO+x4Mlm/br0OPFjk93HpDUq3vnl2pUqZKYWL1S54erdaxWpUoVX8Uc9q/c5vzxh+p17tWz8yt9BjxUu0/n3tktea5X3d/J3b5Px64vvtrZ16nnTb16d37ppX59OvTN3qn9K+1tpYSEhDjbxPxlNS3R+vfCsYS8N8Vb/3OL/Z8Lz+XQ4q6kxGknrP+xr6tmnHY7g1Znc68/7p+T8OT0Qx/u27rr/qr3ZSx55Jr1fDnTTdQCmr4s5JZE/setX7H/1/5rn7O/wP+1IgWWtX0mz4ECGzO0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string E2L {
            get {
                return ResourceManager.GetString("E2L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7H0JnE/V+/+dGcqWpZKlYkiSwuRjq2gukshWRlFhbKMsKWUpMp+skZKsH+tMlkoLIlvJFSU1I6SilRYlEVFZmvn873Pvee495/mc8xmf+v5enZl/9/X6GOc5z3Pu8z7P2e5ZnmPEGYYRth/4C0+JePufu+647/4HBjUfNHDgoAeuTbyzz+CH7x/0QJMGta9rVPu66+s2sP9Tr27SddcmNh8y4JEhg/s0eaDPkEcG9xhwbWKHIT0H3N/rtj6Ppgzq3+eBJvXr163b6Lo+1zfs1bB+/fqBpMLwloucxGu37DNoYJ9HBj9au9ngPg8WsunnD3XfU6zH4F733T+0T6D3wKKDHuzzwANDBvd8uFDvHo/0AKYiRYrEg4qlrzKMuvbfk98VKVE0wf5PKfjnzM8JRvyZ9Hjj6M8JDpyz4XjjYgat+TuDjtVcVOSW+Xtf2L11R80GNXJfueEvO34N461rBA3z6nZuTpTOsP/CfyG1jSwFPrUKZZZ3u734njKbco3S [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string E2M {
            get {
                return ResourceManager.GetString("E2M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7H0HnBTF8v9ckiM8QJQnqGQFJMMSTMgIIqIk5UBQgTvCgSQRJIl6KwgYUKLgEu9IKipBkOADGRDzHQKigj4RDAgiSVEE5fY/NdM1013bvcfq+33ou7/z+SxHV1f11Lerc/dUG3GGYYTtB/7CUyze/ufuu/rdP/iBFg8MGvTA4FoVO/cZOuz+BwY3bVyn/rV16l/XoLH9n4YN6tWvVbHF8IEPDR/ap+ngPsMfGpo2sFbFDsN7Dry/1x19Rqc8MKDP4KaNGjVocG39Ptc16dWkUaNGgXpJ8JZLnMTrtOrzwKA+Dw0dXaf50D5DEm16oRHue4qkDe3V7/4RfQK9BxV+YEifwYOHD+05LLF32kNpwJScnBwPKpasZhgN7L+nvk0uVjjB/k8J+GfaiQQj/mxGvDHhRIID549wvHEpg9Zi6wMnaixKvnXenhd3bdteo3H13Fev/9OOb8d4GxhBw+x2p5sTJRfbf+G/kNomlgKfWtmLV3S/s+juizfnGiXHxVU+ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string E2R {
            get {
                return ResourceManager.GetString("E2R", resourceCulture);
            }
        }
    }
}
