//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Engine.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Engine.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7V0LXFVFt99yBEFQQFEQUEHRfKJAvkpxp6k3S6NS8yt+Kb7ykWiImpk3+nyVqWlZ+chSS0MLrU/NSoXjK81Se6iY5ts07XH1u77yxT2LM+ucOevMBnZ4f2791v/3GzZ79szstWbWrFmzZmYfrYymaQUOwBUQ5OP48/ijAwelD2s/bOjQYemNYnr0zxgxaFh6m+bxCS3jE1olNnf8c3di04RGMe1HPpM5MqN/m/T+IzMz0p5pFJMyss8zg/o+2H9Mt2FD+qe3adYsMbFlQv9WLfq2aNasWVJTX3hL5cLC4zv1Hza0f2bGmPh2Gf2Hl3XElxvlfE/5tIy+AweN6p/Ub2jAsOH909NHZvQZUbZfWmYaJPL39/cBEkPu0rREx/X8cf+gAJvjn2D4c+86TfO58qKP1mSdk52rBT5amGCt/cZhZxu8799x/r4Pf9i8s0Hzejc+vuea4/mltc7niVqWpm9t5bwJ6ej4A+RCadc179Kqha546pHA3aF5N7SQ8WVq [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string A1L {
            get {
                return ResourceManager.GetString("A1L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7V0JfE5H178SkRAhiUiQhCQoCWKJ/W24pbtS7dsVrb211BahVJHW0n500ffjUy3qTTeUaquLIs2jKLVrqaVVS7UUbfG1Yq3vHs+ce+eeZ26SW31/Lt/5/36Tmzt3Zu45Z86cmTkz81ythKZpFw3AFVA2yPhz/919+g4c1HbQgAGDBtZNuq931tC+gwZmNk1v2Dy9YYtGTY1/Gjdq0LBuUtthj2UPy+qdObD3sOys7o/VTeo4rMdjfXu26z3ynkH9ew/MbNKkUaPmDXu3aNazWZMmTTIahMBbKlwqPP2W3oMG9M7OGpneJqv34JJGfOhw/3vKdM/q2afv8N4ZvQaUHjS498CBw7J6DC3Zq3t2d0gUFhYWBCRG1tK0Rsb19x/CypYONv4pD3+ilmla0NmxQVrIMj875y4GaTGCtbafDzqe9nrYzbN2vv3Vqk1pTWv/uaDleeP5xqX+5420HE2Pa+m/ibzZ+APkQmkXtMDSKkcteviu8G1R+X9qkeNKpBy/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string A1M {
            get {
                return ResourceManager.GetString("A1M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7V0JeBXFsh5yEhJCgCQEAgkhC4EbAkRCZFVglO0h60XELVcJGCVhNSQiuBAvCFyQJ/JcPkAQUEERAReQiwk5Aj4QBTc2RSEoqxcVPpFFlrxT53Sd01OnJ8kY38eI9X9fZzI9XT1V3dVbdfUZrZqmaWUuwBUQFuD6c/ugETljxnYbO3r02DEtE4Zk543PGTumc7u09A5p6R3btHP9c32b1uktE7oVjMovyMvuPCa7ID8va1TLhIEFw0blDO+TPXHw2JHZYzq3bdumTYf07I7th7dv27ZtRusgeEtdd+ZpvbLHjs7Oz5uYdnNe9rhAV3zwQ573hGblDR+R81B2xn2ja4wdlz1mTEHesPGB92XlZ0GikJCQAGAx/G+a1sZ1PfN9SFgNh+ufOvDnhiJNC/htcoB2XZFHnItlAVqUEK3bprGnUl8O6blw3/IvtuxMbZdyZWWnS67n5973PG+jFWr61o6em/Cerj/ALuRWrPnn1jBi9T1/r7krouSKFj6lWtKp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string A1R {
            get {
                return ResourceManager.GetString("A1R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7X0HXBPJ+/cmgSQQUgDpodoLggUBCwliPRu207MBKthQUBBEpIkKlkO9szfU8+wFRcEKKKjYQM8CiIIVFEFEpLc3E3bCsmxEzvv9L9473w/L7M7OzD7PzDPPPvPMzAajYRhWJwEIAdTokn8Txsyes8DDwWP+fI8FXUx+dl3kNcdjQb9eXbvZdO1m272X5KRnd8tuXUwcFrt7L17k2m+B62LvRS7uXUwcF093nzNjmKvfOI95rgv6WVl1727TzdXWeoa1lZVVD0tl8BRNaeFdB7t6zHf1XuTXtf8iV08lSTzLp/45qi6LZsye4+PaY+Z8FQ9P1wULFi+a7qU008XbBSRis9l0QKKgPYZ1l4RfXrPVVBiSEz74l1KDYfTKIDp2raaenao6OtYKZ83hmsenTn+wB+1OP/RXUkqnXh1qj/eultxfg6ftjgVjYh3b+gvBIMk/QC4o7QrWtDQ99VPTRnMeqcfXYoJQmtmnn/T9dEBpK/H7Ajp+QsePxvgkahJV [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string A1S {
            get {
                return ResourceManager.GetString("A1S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7V0HfBXF1p8kpBESkhCICQlcJPTeI3URBUVF5Ak2kBoEBIIRkCIQH1IegiDoR7EAClaKBUEQzKXDE3mP9qHYKKIi+gQERFrePblz7p09dzbJEr4fC9/5/36bzc7MmT3nzJkzfa8IEkLkegB3QIlgz58HOvXrPzizTeagQZmDa7q6ZGQ92T9zcIvGteul1653S/3Gnn8a1q9br6arzbCBQ4dlZbQYnDFsaFbPgTVdHYf1Gti/910ZI+/PfDxjcItGjerXT6+XcUuT3k0aNWrUoG4ovKVUXua122VkDsoYmjWy9q1ZGUOKecLDh3vfU7xnVu9+/YdnNOgzKDJzSMbgwcOyej1ZrE/PoT0hUURERDCwGFtFiPqe++kjESUiQzz/lIQ/zdYKEXx+XLCos9YrzoXcYJEgRWuzIfNE9Tci2r765Vu7N+2s3rjq5SVNL3ri//zUG19fZAtj6y3eh9i2nj/ALuR2SQTmlhS3/NH7ovbG5VwWseODbj7RPnlkIuS2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string B1L {
            get {
                return ResourceManager.GetString("B1L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7V0JeBVF8u/cF4GEAAEE8rjkPkM4VGAEFNeD9UIO/ZAryBGODQQ5dMl+igYEFXRVVECUQ+RwRURkhTxBQARROeRUYBERWV1cCbfwf5XXNa+nXs9LhrgfA//6fV9nMj19VFVXV3dX97wRYUKISz7AFVAq3Pen270DBw0b3nH40KHDhzX0PJCZPXLQ8GFtWzZu1rpxszbNW/r+adG8abOGno45WaNysjPbDsvMGZXdJ6uh5+6cvlmD+t2ROfb+4UMyh7XNyGjevHWzzDat+rXKyMhIbxoFtaQUFt64c+bwoZmjssc27pCdOSLSFx8z2l9PfJ/sfgMHjc5M7z80bviIzGHDcrL7jozs32dUH0gUGxsbDiQm1RGiue968nBsqbgI3z9l4E/yP4UIPzchXET908/O+UvhopxkrePa4SfqvxV768zdC7Z9urV+y7oXF99wwff8i1X+581FrjBSb/DfJN3q+wPkQmm/i+DSKiW/2+uehB3J+RdF0hNhNU7cXnls [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string B1M {
            get {
                return ResourceManager.GetString("B1M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7V0JeBXFsm6yAEkIZAFiAoGwyRYQwiKIyMgi1/UBsiiyCgmghGAEPgGRqGxG9CFXVK6gqBcXRJBd2XJAVsnlCgQjoAh6UREXZJGwhXuK03VOT52ek4zxPQas//smk+np6qnqrq7urq6ZI0oJIS65AWdAuSD3n17dhg4bkdEhIz09Y0RyUs/UzEeHZYxo27Jx01aNm7ZOaen+p3lKk6bJSR1GDx81OjO17YjU0aMyBw5PTuoy+sHhwwbdmTq2e8bDqSPatmiRktKqaWrrGwfd2KJFi2ZNQuEpsZcLb9w5NSM9dVTm2MbtM1NHhrjTy4zxPCd8YOagocPGpDYbnB6WMTJ1xIjRmQ8+GjJ44KiBkKls2bJBwGJUXSFS3OdT35YtFxbs/qcC/GmzVoigcxODxA1rPeKcvxQkKkrROmzMON7grbK3zf3ind2bdjZoWa9w4U0X3PfPrPHcTxFZwtja2nMRdZv7D7ALpa0T/qXFRy/u1zUiLzqnUEQ9Xarm8TsS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string B1R {
            get {
                return ResourceManager.GetString("B1R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7V0JeBVF8m9eCDkgkHAFAoEHYgwREAiHuGIGEFD4y6Ic67oi4QgCAsFwKIKSVRRW/aOry18FUZSPQ2BRUFn1S8wjIKhE5BQvBERU8AAPQBDN/1Ve13s99bpfMsB+zGbr932TyfR09VR1V1dXd9fME1WEEKV+wBlQw+P/86cbRo+ZkNsjd/z43AmtvINz8iaNyZ3QtVObdpe3adelfSf/Px3at23XyttjyrjJU/Jyuk7ImTI5b9i4Vt7+U4aPGzOib860gbm35Uzo2rFj+/aXt8vp0nlE544dO2a2jYan1CkrvE3vnNzxOZPzprXpnpczsao/PWZq4Dnxw/JGjB4zNSdz5Pi43Ik5EyZMyRs+qerIYZOHQabY2FgPsJh4iRDt/eefD8bWiIvy/1ML/pQUCOE5PdMjfAUBcX4t9Yi6UrQexbnHMhbH9lr44bIdG7dmdEr/fdUVZ/z358i87UW+sO7oErhI7OX/A+xCaYUivLSGSS/ecn31XUlFv4vE+6o0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string B1S {
            get {
                return ResourceManager.GetString("B1S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7V0JeBVFtq4kbAlZIWEPBBACYQ1hXxtQYRRZXRBEIBAejEAgLJ8omigIPhcWkVHGQVFx9CGgoDjIlquDwswgQsDHpggi4IJDYFhEkbx7cuvcrj63+iZNmJeGOf/3VTpdXaf6nKpTp05tfUWIEKLAC7gCIkO9f+4ZOHbcxMyemRMmZE5smnR3RtaUcZkTu7Rtntq+eWqHVm29/7Ru1TK1aVLPaeOnTsvK6DIxY9rUrJHjmyb1n5Y+ftyo2zNm3Jn5QMbELm3atGrVPjWjQ7tR7dq0aZPWsiy8pXJh5s17ZWROyJiaNaN5j6yMSWW88eWn+94TMTJr1Nhx0zPSRk8Iz5yUMXHitKz0KWVGj5w6EhJVqFAhFFiMTRailfd67liFyPAw7z8x8KfTJiFCf8kOFS02+cT5tSBUxEvRen6cmZ/yeoVbl+5/M2/rzpS2ja6s7HjZ+/ziRt/zViJHGNs6+G5ib/X+AXYht99EYG7V4965f0DFvXG5V0TsrJB6+bfV [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string C1L {
            get {
                return ResourceManager.GetString("C1L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7V0HfBXF1h9SSCEJCQlESiAQCL2E0AWygiCIDZ8VC1KClAAxFEV9cu18vg9siCK9iWJB5YkShFz14fMpIAjPADaKKAgiaJCikO+e3Dl3Z8+dvcmK/lj4zv/3m2x2dmb2nDNnzsycmbkrKgkhSn2AKyAuzPfn+quHjxgztufY0aPHjmmRfl1uwbgRY8d069Aqq1OrrM5tO/j+ade2TVaL9J4T8sZPKMjtNiZ3wviCQXkt0q+aMDhvxJB+uZOuGTsqd0y39u3btu2Uldu545CO7du3z24TCW9JLiu81SW5Y0fnji+Y1KpHQW5+hC8+aqL/PbGDCoYMHzExN3vo6Jix+bljxkwoGDwuYuig8YMgUXR0dBiQmNhYiLa+a8me6LiYcN8/VeFP0mohwk5ODhORq/3s/FYaJlIkaz3fH3u42aLo3nO2Lf3sXxubdWhy+pUuv/uebyj0P28rPMJI7eK/Sezt+wPkQmlrRHBpNZOW39q/ytakotMi8cFKDQ5fWmtS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string C1M {
            get {
                return ResourceManager.GetString("C1M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7V0JeBXFsu4kLElYkkBCEkggAZJAZEnCvmYEFb24APoUUXaCRpZgAngVfRxFkI+r4gbuyxX3DUV9AhFyQBB4egEJiIj4iCyCXhAQUbgI91RO15meOj1Jhuhj4Nb/fZPJdHf1VHVXV3dXd88RIUKI0z7AHVA31PfnukE3508s6FswYULBxDYp1+YVFuUXTOzVuV1213bZ3XI6+/7pmJOV3Sal75Txk6cU5vWamDdlcuHI8W1SBkwZNT5/dP+8268pGJc3sVenTjk5XbPzunUZ3aVTp04dsmrCWxqWZ96uX17BhLzJhbe361OYN6mGL7z2VP97IkcWjr45f2pehzETIgom5U2cOKVwVFGNMSMnj4RE4eHhocBidIYQOb770V3hdSPCfP9EwZ8eHwsRemJ6qGj/sV+cf50OFbFStL4rCw5lLgi/5NmvXt20an1m51an3up+0hf/a7E/Pkd4hLGmm/8h+hLfH2AXclsmgnNLjFk4bGCdzTElp0T0jJDmh/7S [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string C1R {
            get {
                return ResourceManager.GetString("C1R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7V0LeBXVtd7JCZAEEpLwCK9oCAQiIiYECA+BURRabanSgl5UBEJQKhAID8FrS8S3n1UaX7cWFB/IFSytorUXhBwEBC2iPKwKgoQU0YIW+HhWJfesnL3O7Fln73POEPoxpOv/vslk9uy1Z6211177tWaOiBNC1AQAZ0CT+MCf64fdNmFy6aDSSZNKJ3fNHlFSNm1C6eT+vboV9O5W0Kd7r8A/PbrnF3TNHjRj4vQZZSX9J5fMmF42ZmLX7GtnjJ04ofiaktm/KL29ZHL/nj27d+9dUNKnqLioZ8+ehfkN4CnNagvvNqSkdFLJ9LLZ3a4oK5mSEEhvNDP4nOQxZcW3TZhZUjhuUlLplJLJk2eUjZ2WMG7M9DGQKTExMR5YTOssRPfA+Wh1YpMkX+CfpvBn09tCxP9rTrzwvx0U57uaeNFcijbondJDXV5MHLzg08Vb123u0ivv9Kt9vw/cf1Dm7S7KhXVHn+BF2uDAH2AXSlslwktrnf7HUdc13p5eeVqk [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string C1S {
            get {
                return ResourceManager.GetString("C1S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7D0HXBNL8wchBVLpHUKxNxRBRIGzd0V99kJRsSEgCCooRrFgx/bsvXcURUWRUGxPxK6gqFixoOKjCEj5Z5Pb5LK5qPm+9/1f3vu5v99x7Nzu3szs7O7c7MwG08EwrE6SwB0kjq7kz5ABEyaGhHYKnTIlNKSpcPC48IiJoSFe7s1bejRv2baVu+Sf1q1cWjYVdooMnhYZPs4rZFzktPCA4KZC38jA4Iljeo2b+Vvo5HEhXm5urVp5tBzXts2YNm5ubq4udPAWY2njzbuNC50yblr4zOYdw8eF6UngzCjZewwCwsdMmBg1znXsFP3QsHEhIZHhgRF6YwOmBYBCLBZLF6AoaIBhrST30pcsjj5N8g8f/BlD08V0q+boYkNoulJyvtXpYiYEaZ0yQosb72Z13Zq7/05WTmP3hrVHPKslz+2Jsq0wEYavGiIrLJgg+QPQBa2lEi2QW7M0PD66P/ueYVotJojTcSzuaTXTHLS2gHgu0CX+0SUu5VTsowKSwdNQ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string carport1 {
            get {
                return ResourceManager.GetString("carport1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7V0JeBVFEu5cJBAwL0BICCSEcCNXCOESNgMKKIcCKupKuIOCXAZBUIG4LLuIsqIfuiCKKLoeICC4GBSSRxYBXTYIopGVS5RVFAQWEEEw+yqv672eej0vGeD7GNj6v68zmZ6unqru6qu6ep4IEUKUeABXQOVQz5+7+t8/atz4G8ePHTt+XLOUAdk5E0eNH9e5bYu09i3SOrRu6/mnTetWac1Sbpw05qFJOdmdx2VPeihn6JhmKX0nDRszaniv7Kl3jH8ge1znjIzWrdunZXdoN7xdRkZGeqsIeEu10sxb9MgePzb7oZypLbrmZE8I98RHTva+p9LQnOH3j5qcnT5ibMXxE7LHjZuUM2xi+IihDw2FRFFRUaHAoquREK0911PfRFWuGOb5Jwb+fLpdiNBzM0LFpu1ecX4tCRXVpWg3Fo4/3nRpVPeXvnxj56aipm0b/7a843nP86dk2tYiVxg1u3pvXH09f4BdyG2DCMytZuzKQf2id8UW/CZcM0NSj/dM [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string D1L {
            get {
                return ResourceManager.GetString("D1L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7V0JeBVF8u8cmARISAiYQAKJ3Ee4Ek4VMyKIAiqg4sKCSiALQY6YgAuK8BS8VjGy4gGioCC7oHLo/jFigIfKCrsoGkBQVoUoigeIByqI8n+V1zXTU6/nJQO7HyNf/b6vGV5PV09VdfVVXTMREUKIkwHAFVA7MvDPdYPHFkycdMmkCRMmTczKHJJfVFwwaWLPru07dW/fqUd218B/Omd37JSVecmU8ZOnFOX3nJg/ZXLRyPFZmQOn5I0vGNU/f9o1k27Kn9izS5fs7O6d8nt0G9WtS5cuOR1rwFOSKytv3zd/0oT8yUXT2vcqyi+MDuTH3BJ8Ts2RRaPGFtySnzN6QtykwvyJE6cU5RVHjx45eSQUio2NjQQWE1sKkR24/vBJbO24qMB/6sA/JQeEiDw+M1LMOhAU55eTkaKeFO2S1yYdabMk9tIn9/yt/I2323Rt9dvz558I3O8vy2YLnzDS+gd/JA4L/APsQm3rRWhtDZJWXT+o1s6kjb+JxFkRTY70 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string D1M {
            get {
                return ResourceManager.GetString("D1M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7V0JfBVF0u8kJCEkQAKBhCRAOEUWkRCCXDEDgqxyGFgQdOUmICiH4cYIUVAR4dP1Q12U5VRxucXlXEIeLAi6Ai4CATmEALqKXJ+gHGq+V3ld7/XU60ky4v4Y2Pr/fp3J9HT1VHVXX9XV80SAEKLADbgCIgLdf3p0fXzI8BH3jRg2bMTwBokPZ2SOGjJieGrThknNGiY1b9zU/U+Txo2SGiTeN+bJ0WMyM1KHZ4wZndnvyQaJ6WP6PzlkQIeMCd1GPJExPDUlpXHjZkkZze8ZcE9KSkpyo2B4S8XCzBu2zxgxLGN05oSGbTIzRpZyx4eO9bynTL/MAY8PGZuRPHBY2IiRGcOHj8nsP6rUwH6j+0Gi0qVLBwKLkXcI0dh9vXSydERYkPuf8vDnsz1CBF6bHCi27fGIc70gUERL0e7bOuJC/UWl7//LwcV7t+2u37TeL8ta/OR+PkOmbSyyhVGljecmMt39B9iF3HKEf25Volb27hK+Lyr3FxE5JaDmhQfj [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string D1R {
            get {
                return ResourceManager.GetString("D1R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7V0LeBVFsu48ICEkIYFAQhA4vENkkQCBgLIZkIe4KyDGXRcUeRgUFwI3BBR1IV7wruAqPnCv6wNRVu+KLKKoRBfIgesDFRAVCYooQUFB0eiCgAvknsrpOqenTvc5GcJ+jLn1f99kzvR09VRVV1d3dfdMRJQQotoHOAMSo31/fjv6hilF0y+ePm3a9KJunt8UFs+cMr1oQJ/uOXndc/r17OP70btnj5xunotnTS2ZVVw4oKhwVknxhKndPKNmTZw6ZdKvCucUTP99YdGA3NyePfNyCvv1ndQ3Nze3V48G8JRmNYV3H1Y4fVphSfGc7oOKC2fE+tLjZvufkzCheNINU2YX9rpuWqPpMwqLimYVT5wZe92EkgmQKT4+PhpYTOkiRE/f+cjn8YmNYnw/msCfLeuEiP5pXrTwrvOL86/qaJEmRbt40/Sq7OXxQx/b9T/vv7Ytu0/W6ZX9T/ru3ynz9hSlwrqpn/8iZajvD7ALpa0XoaW1TH1u3OWNd6SWnxYp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string D1S {
            get {
                return ResourceManager.GetString("D1S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7V0LnE3V/l/OzDAGzYwZjaFhvGeGPIbxqmEjRpFGHnWLPMYQYdwJqXSdHtzuvXIpvcikW109pFwKMeMINxVuJKP8KYWSyyV5JMz//Oas3zlr/87aZ2anPm36fT+fNXv22uu39u/3W7/1/q2zRQUhRIkXcAVUdXn/3HLznaPH53XLGzcub3yz5IG5+XePzhuf2bZ5q/bNW3VIb+v9p016y1bNkrtNGjtxUn5u5vjcSRPzh41tlpw9afjY0Tm9cu/tn3dX7vjMjIz09Patcju0y2mXkZHRumUEvCWuNPPmWbl543In5t/bvGt+7oRwb3ylyb73RA3Lz7lz9OTc1iPGVc6bkDt+/KT84XeHjxg2cRgkioyMdAGLMU2ESPdef/g6smrlMO8/0fBn9RohXGenucSba3zi/FTiEvFStG7v5R1LezGyx4Jdi7Zv2JrWNuXC4o7nvM/vkWnThVsYWR19NzE9vH+AXcitUATnlhj75h19q+yIXXtBxDxcof6xG2rd [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string D31L {
            get {
                return ResourceManager.GetString("D31L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7V0JdBbFsu5sZGFLIJCwBwLIEoGEXcUMsl1BQNCH6OGCQKKArGETn8vP6oYouFw2lftAVBAUPSrI9iPrfQKyXFnd2FRUvDwFQdneX5mumZ76e5KMXA8Dt75zOpPp6e6pqq6u7q7u/kdECCEuhQBXQInI0J+7ug8YOHRYm2FDhgwbmpHWIzdv5MBhQ1s1a5DZokFmy6xmoX+aZDXKzEhrM3rwqNF5ua2G5o4eldd3cEba7aP7DR7Yv1PuuDuHPZA7tFXTpllZLTJzWzbv37xp06aNG8XAW8rmF96gQ+6wIbmj8sY1uCUvd3h0KD52jPmehL55/QcMHJPbOGdI/LDhuUOHjs7rNzI6p++ovpAoLi4uEkhMvE6IrND11JG4EvFRoX9Kw5+klUJE/v5YpIhZabJz7lKkSJastfl42Ml68+Pav7zv9V0bttdrVufiWzecDz3f9pH5PEsEhJFyg3mT2D70B8iF0laL8NIqJL3du1vxfyatvSgSJ0bUONmx4rgU [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string D31M {
            get {
                return ResourceManager.GetString("D31M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7V0JeBVFEm6SQE7ICwQC4QoGFBCBBMIhYEauKNeCcumqCCQICgQDAq4rPBbBm/WCVW4VRFHZVUSQKw8QxA9FxAPWMxEUPEDXFVG59lVe13s99bqTDNHPka3/+yaT6e7qqequqa6u7pknKgkhzvgBZ0BChP/PkCtGjxmf3y1/3Lj88S3SBucVTByTP75Lu5YZHVpmdMxs5/+nbWbrjBZp3W4ZO+mWgrwu4/NumVQwfGyLtP63jBg7ZmTvvFsH5t+UN75LVlZmZoeMvI7tR7bPyspq07oy3KVGSeUtc/Lyx+VNKri1ZdeCvAlR/vToyYH7xA0vGDl6zOS8NrnjYvMn5I0ff0vBiIlRucMnDYdCMTExEcCi5wIhMv3nHw7EJMRG+v9JhD+dNgoR8cv0CNFqY0CcE2ciRLIUrdvW/O+aPxnTc9H+FXtf3d28XdPTz1180p9/fEMgP1N4hfVax8CFp6f/D7ALtW0S4bXVSfrndQPi300qPC08Myud912v1FtT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string D31R {
            get {
                return ResourceManager.GetString("D31R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7V0JfFRF0u/MBBIghAQSwk24zwUChksgj9uDFZHLdVEJECQICV+4FDxG0RVdP1g/1xMFFlbkUlcOBbkGAZfdRY3AAgu7KIKyiPwW8AQjfFOZrpmemu6ZeUZ/PrL1//1e3rx+Xf2qqqurr3ovIk4IcdkHOAOSXL4/I2+akF9Q2Ldw8uTCgraZI/KKpuYXFvTs3C6ra7usbh07+35c1bFDVtvMvtMnTZtelNezIG/6tKLcSW0zb5w+ZlL+2Ovz7h5WeGdeQc/s7I4du2bldesytkt2dnanDhXgKTVKC283MK9wct60orvb9SnKmxLvS0+Y4X9O5dyisRPyZ+R1Gje5UuGUvIKC6UVjpsaPy52WC5kSExNdwGJKCyE6+s5fHk9MquT2/agGf/ZsEcJ18X6X8G7xi/PdZZdIk6L1fbvwbOuliQNePPTy3p3vte7c8tLq7iW++3Nl3o7CI6yZ3f0XKQN8f4BdKE1mCCmtduprtw2psj912yWRMieu8dnr6tyd [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string D31S {
            get {
                return ResourceManager.GetString("D31S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7V0JeBRF9i9ykHDnAELkCqch3CBySdKIgNciICp/QIywiYAQYiBcCzKI4AEL4rXLQgRWUeRwVeSUkAFEXO5TIJ/gtYqorHiAIGD+82bqzVS/qZ6kwf1o8f2+r1Pp6nrV71W9qnpV9apHlBJCFHkAIaB8mOfPfb2HDM0a2WXkiBEjs5ok3ZuRM2royKxONzZr2a5Zy/atbvT8c0OrFi2bJHXJHT46NyejU1ZG7uicB4c3SeqZO2j40MF3ZIzvM/LhjKxObdq0atWuZUb7toPbtmnTpnWLSHhLvDfzZt0zRo7IGJ0zvtnNORnZEZ74qDG+95R9MGfwkKFjMlr/eUSZkdkZWVm5OYNGRfz5wdEPQqLo6OgwYDHmeiFaecKfPo8uXybc808l+NMxX4iwXyaHieb5PnEuFIWJylK0LptHnk55Obpb3pHX9r+3O+XG5F+Xd7joef7zBt/zVsIljG0dfDcx3Tx/gF3ITWZmyi0x9l8De5U7GFvwq4iZWqru6duv [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string F1L {
            get {
                return ResourceManager.GetString("F1L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7V0HeFVF9h+SkEYghRI6AQRDgrTQkZdLLytFQLAgJSFBFBKks7DwKIuI0teCLG1RkbKgiyA9D0IAKcICGgF1EXAFXaVXkfzveW/Oe3PPmxu4svtx5T+/75tM7tw5M+ecOdNn7mMFGGN5OsAHRATof3p0eWFARmaLzEGDMjOqx3VPGzJ0QGZG0/o1ajesUbtRnfr6P3Xr1KpdPa7F8IHDhg9Ja5qRNnzYkL4Dq8d1Hp4ycEDqH9JGd8t8KS2jab16deo0rJ3WqEFqg3r16iXVKgi5FHUnXqNNWuagtGFDRtdoPiRtcJAeHjLCk0943yGpLwwYkZbUb1BY5uC0jIzhQ1KGBvXrO6wvRAoNDQ0AFqMeZayO7l85HRoRFqj/Ewl/PtrCWMCt8QHsvS0ecX7JC2DFuGgtdmReSFga2nrBl8sO7/wsoX78nVWNb+vvB/G4dZiTabFNPA9RrfU/wC6ktpX5p1Yqek2vJwsdjc66w6ImFah0oX3p0bGQ2p/5+6gA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string F1M {
            get {
                return ResourceManager.GetString("F1M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7V0HeFVFFh5SSCAhhZZCC00hdCJdkot0dWmKZQkoYAKs0ougCA8UZUGqnRpdFxEEdRGkJo+qCxiFAIEgKogNGyqg1Ow97855b+55c19yYffzws7/fTc3d+6Uc86cOTNzZuY+VoIxVqgD7oDIIP3Pvb0GDxk2vP3woUOHD6ufdE/GqNFDhg9r27xhk5YNm7Rq2lz/55amjZvUT2o/9pExY0dltB2WMXbMqP6P1E/qMXbAI0MG3pEx4e7hD2cMa9usWdOmLZtktGoxsEWzZs1SGodCKeU8mTfsnDF8aMaYURMa3jYqY0SIHh42ziindP9RAwcPGZeR8tDQUsNHZAwbNnbUgNEhD/Uf0x8ihYeHBwGJMTcz1lS/n/kyPLJUsP5PNPzpk81Y0IXJQax7tsHOxcIgVp6z1n7b8NPJ/wjvtPjwG/t35CY3r3PlrdaX9PdxPG5T5mJa5zbGQ0wn/Q+QC7ltYf65JcS+3a9nxIHYnCss5skSNU7fnjghDnKbxt/H [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string F1R {
            get {
                return ResourceManager.GetString("F1R", resourceCulture);
            }
        }
    }
}
