//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Engine.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Engine.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7H0FeFRH1PYNGpyQoMUhuIdStLkFinuBFvfFIWiBIosVKIVAKbLBggR3bwnkQnGCBy0SpLgTtJD9s3vn3LtjWfp9//Nwsh/zPJDMubOb8573nDNz586dUbwURbHHFcdPR0mdKO6/75t0696nb7W+vXv37VMsd/Mu/Qd079unSrkSpcuXKF2hTLm4X8qWKVW6WO5qg3oNHNS/S5U+XQYN7N+hV7HcjQZ17NW9U90uQ5v27dmlT5UvvyxTpnzpLhW+6vTVl19+GVAqqeOv+Dq/vETNLn17dxnYf2iJqv27BCWJkycfrP+dlB36d+rWfXCXgM69U/QN6tKnz6D+HQck6dxhYAdHI29v70QOFdMXVJQycT9jbnqnTpE47pd0jv9+OpBUSfRuVCKlb9wvjvKvPZHiR6BV29v3aZEl3jXmX1h+et/xIuUKxa6p+D7u+lekbRnFqqjbH+iWSG+J+yuOXx3ftot8g+u3ZfVZ37ZxqiifiFgl/VivvE/rZBua2fFt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string A1L {
            get {
                return ResourceManager.GetString("A1L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7H0FdBXH9/+SBLeEBCtQKBbcghfI4u5SaJFgAYprgSIPCTRFgjRAQoEADRR3CBDIYsWCOxR3dy3k/d+8nft2ZnbmPfo9/99h8k7nnCXM3Tvz7ud+xmd2V0miKIrVFtBfFNJ42P75rln3Hn36Vu/bu3ffPkVyteo6YGCPvn0qly1WsnyxkhVKlbX9p3SpEiWL5Ko+uNegwQO6Vu7TdfCgAR17FcnVZHCnXj061+86rEXfnl37VC5TplSp8iW7VijXuVyZMmUCSiRFv+Jrz7xY7a59e3cdNGBYsWoDuvbzssmTD9F/J1XHAZ279xjSNaBL75R9+3Xt02fwgE4Dvbp0HNQRKaVIkcIDmejtryilbH9f3UyRJqWn7T/p0T/nFngpHh9GeyiHF3jZ4fxj9VD8MLTqu/s+K7Q4Ra1555ee3Hu0UNkCCSsrfrTdn4l1SykWRQ2ZonvC+5HtL/ovym0HzoHMLavPmvZNU5/2iUtQvMclyf2s3lfDMqPcQvB9bw/8 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string A1M {
            get {
                return ResourceManager.GetString("A1M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7L0HWFTHFzZ+QUVUNKJYE7GLsQv2xrVExa5RY+9iL7FrVNZeIxrrYsNCYq9RURGuRmJbe+9ojEajqCh23Y/dO2fvnbkz4O97/t/fs/tknidZ59zZ5bzznnOm3hnJTZIka1KyfdqSl3vS/35o0bvPwEG1Bw0YMGhgiXytew4Z2mfQwOoVSpWtVKpsZf8KSf8o51+mbIl8tYf3HzZ8SM/qA3sOHzaka/8S+ZoN79a/T/eGPUe3HNSv58Dq5cv7+1cq27Nyxe4Vy5cvH1Amje2vZLX/eKl6PQcN6DlsyOhStYb0HJw6SZ52hPp30ncd0r13nxE9A3oMSDdocM+BA4cP6TY0dY+uw7raCnl6errbVMzsJ0n+SZ8v//L0Spcq6R9f2f63vLmH5P4uxF2al/QPW3pvdZd8CLTahwY9K7bGs+7yK7+dO3yqWIWinzZV+ZD0vC0p6y+ZJLlpbnd7JvOKpE+burZfO0B+Qf9ruby3dmqe4YJ3zCcp8yS3As8a5B6d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string A1R {
            get {
                return ResourceManager.GetString("A1R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7L0HWBVJ07A9GDGLmFcxi6uuAcyJMayKWVfdNSc85pxdlaOiKyYMazgYwIBrzoFVlNE1C+YcMUdQEcw6P+dM15npnh7wff/vuyzOZ1/X87BVM2DdXVXdPd09PYKTIAhyQrH+tJaMKRL+7/dWvfsMHFR30IABgwaWLti259BhfQYNrFmpTPkqZcpX9aiU8B8VPMqVL12w7oj+w0cM7VlzYM8Rw4d261+6YIsR3fv36dG455jWg/r1HFizYkUPjyrle1at3KNyxYoVPcultv4rrrY/XqZBz0EDeg4fOqZMnaE9B6dK0Kcdqfw76bsN7dG7z8ienj4D0g0a3HPgwBFDuw9L5dNteDfrTc7OzimsJmZ1FwSPhJ9x950zpkuZ8B9ZrP+Xf2xaIcVH3xSCS8J/WMsnOYWQnaDVPTToVclVzvWXXf3n/OHTJSuV+Lqx2ueE69fGKPd6CGZBrD02hU3Imjvh71nNtf61/eQvaP9aHpctnVtmuOgS/lXIOtmp8KtG [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string A1S {
            get {
                return ResourceManager.GetString("A1S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7Vp7bJNVFL/r1q3tNrq68UyIoH+IOOYeDjYiUpwyIsYAQc1MBMYoYZG1MDaSxQdLEP/QaCBRI4KIQjIEie9XDIKLZhIZ8nQYjSAEI/rPfEQeymrPds96enq/b21nk6u5v+Rre9/nd173fjcVGUKIcATwDchzRD7uX7CiMRiqCTU1hYLFE+4LNK9pDAVnTC0pqyopqy6fGvlxS3lpWfGEmtaVLa3NgRnBQGtLc/3K4gnzWpeubGyYG2hbGHooEJxRWVleXlUWqJ7WMK2ysrKi1AmrFPZPXlIbCDUFWprbSm5vDqzKitTnrB1Yx1Pf3LCicW2gYlmTO7QqEAy2Ni9dk7WsvqUeOrlcLgeIWHCDEOWR7z/OufLcmZEfXvh4p0oIx5V1DtFRNUDnr7BDFElqNZ2h3sk7XLNfOtVx7LPDk6dO6nt9+t+R9pDsWy7ahX9W4UChYEzkA8SF2faJ+NnG+t5YND/3hG9/nyhYn3Fd713j2kbDbBtke4FD/nDIJxa9 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string carport1 {
            get {
                return ResourceManager.GetString("carport1", resourceCulture);
            }
        }
    }
}
