//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlotPlanning.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlotPlanning.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7H0HnBVF8v88lgUkSFriEpYgLDksWeANGQURJAsoQRAkR8msAQFFwXggiCCgoh4q5ykguKNiBEUFFU9RUCQIKiIKh4H/1EzVvJ563W93dtk/zf22PzRvp6erur5d1WG6Z6qNkGEY5+0AvxAK5rL/63PdyFHjxrcbP3bs+HG1k/oMnzR51PhxrZrUbWD/a96gef26TevXb1A7qd3UMVOmThreatzwqVMmDRlTO6n71KFjRg3rMnxGr/Gjh49r1bhxw4bNGgxv3nRY08aNG6fUj4dCiju863YaPn7s8CmTZtRtO2n4hNx2et5pbjH5h0waNnLUtOEpN429bPyE4ePGTZ00dHLum4ZMGQKZ8uXLlwskLFLdMBrav8u+zFfwsjj7j8LwX9wLuY1c5+blMs48n9tB88f5XEYCImv3xviTNdfm6/jYvqc+2fFhzSbJfz/X4k/7fhrmbWikGmbvVm5FFFls/8KfwG07chC5lSn6/A09Cuwtmva3UeSOUOWTV5ed [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string A1 {
            get {
                return ResourceManager.GetString("A1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7H0HfBTF+/dceiMFQm8hIIReQofkliZVREVBKUYQBOlVQJQAKiBIEVEQBKRI8wcCShPIiUiRIgIKSA0C0pSA9PruszvP3txzs5cckD+LL/PJ5HbKM/N853mm7OwUZmOM3VMN/IIJ81H/vfR8p87de9Tp0a1bj+6lYl7q0LtP5x7dEyqXKa/+VStfrVyZKuXKlS8VU6df1779endI6N6hX9/er3UtFdOsX7uunds37jCweY8uHbonVKpUoULV8h2qVWlfpVKlSvHl/CGTbFraZep36NGtQ9/eA8vU7t2hp5/qH9hfzybktd7tO3Xu3yH+9W7BPXp26N69X+92ffxef63vaxApKCjIBziMLMZYBfV38sGgsGBf9SEC/vWt6st8bg7xYZ2q+mpobt3zYdEcWZ0NPdJKzA56+ov983Zv3Fmictzdr6vfVsPL8bgVWDJTqhzVI0fmUHkFdiG133gKYmq5o5a0fS50b1TKXRY53Bab1ijPwJyQ2hc8PNKHP8Cv [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string A2 {
            get {
                return ResourceManager.GetString("A2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7H0HfBTF+/dcQkggAQKE3kIRQu8QSnIrvRdFmqChg4I0CyhKAFFQwYL4A+kgzYKISBPMiaCiNEEEBZUuUqSIgCDw7rP7PHtzz80muYS8bvwzn0z2pjwzz3fmmd6ESwhxW1fwBRURpP/rfN/AQY8NbTx0yJChj1WK7txvxMhBQx+Lq1Oluv5Xr3q9alXqVqtWvVJ04ycGP/7EiH5xj/V74vERvQZXiu7wRO/Bg/q07je609BH+z0WV7t2jRqx1fvVq9unbu3atWtWC4FI8hphV2neb+iQfo+PGF2l0Yh+w7Lo9qFPmtFk7zWiz8BBT/ar2XdItqHD+j322BMjeo/M0rfX473AU1hYWBBwGFlOiBr6d8bBsIhswfqPXPBvdrNgEXR9bJB4rVmwgebG7SARhcgabx56ocKisGZzDizds2VnhToxt96v/4/u3hX91hCJQlt8zPQcWVTnFdiF0PZhCHJohXJ/+FDH8O9zJ90SkRNcpS60Kjy6AIQ2B90jg/AH [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string A3 {
            get {
                return ResourceManager.GetString("A3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Capture {
            get {
                object obj = ResourceManager.GetObject("Capture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CarPort {
            get {
                object obj = ResourceManager.GetObject("CarPort", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CellularStreets {
            get {
                object obj = ResourceManager.GetObject("CellularStreets", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CullDeSacStreets {
            get {
                object obj = ResourceManager.GetObject("CullDeSacStreets", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CutAndFill {
            get {
                object obj = ResourceManager.GetObject("CutAndFill", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7V0HfBTF958kpBBCCr0nht5L6CS5o4MiIKAovUsTogjShCAgRbogTRCQIiAIAoKiJgRRfnQpgmAhUqUoAtJE+O/bm7c39242yWHyd4Pz/WRyO7PzZt+bmTdld+YN82KMPdQAv4Agb+3fc6169xkwsP7Al14aOKBcxHM9XxnUZ+CAmOoVKmt/tSrXqlShRqVKlctF1B/c/9XBr/SMGdBz8KuvdO1fLqLl4G79+3R/quewNgP79RwQU61alSo1K/esVaN7jWrVqkVV8oWH5NTTrtC458CXer76yrAK9V7pGZdFC/cf4nhMYNdXuvfuM6RnVI+Xsg6M6zlgwOBXug3K0qPrq10hUkBAgDdwGFqSsSra77xTAUFZfbSLEPjXIs6bed8b7c3qx3nr0vz10Jvl4pLVTxp4rcz7AY0WnVh1+KsDZaqXevBh7fva/Ww8bhUWz+z7Vzsihx7V/gG7kNoXPAUxtfxhH3V6JtvRsIQHLHSsV+S1JwsMywupjef3Q735 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string E1 {
            get {
                return ResourceManager.GetString("E1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7V0HfBTF959LTwhphB4gBAgQei+S3NERlF5E6V2QIorShNCkNwERUAQpUkQBRUAEAogiXYoCgkoX4acoHVT+9/bm7c29m83lgPzZ4Hw/mdxO3fdm5k3bmTfMwhi7bwf8AkJ97P9aNu3xYp++Nfv27t23T/HYll37v/Ji3z6JFUuWsf9VKVOldMlKpUuXKR5bc8BLrw7o3zWxT9cBr/bv+FLx2MYDOr30YucGXQc179ura5/EChXKlq1cpmuVSp0rVahQoVxpf3hJFi3tknW79u3d9dX+g0rW6N+1n5/dPfA1x2tCOvbv3OPF17qW69I7uG+/rn36DOjf6RW/Lh1f7QiBgoKCfIDCiMKMlbX/vvNjUGiwr/0hHP7ZOvown7vDfVj5jj4aN/fu+7BozlnN7X2vJiwKqvPesQ8PfbU/oWKRfz+q+rfd/+8OjrBlWTKztV/iCByx3/4PyIXUNvMUxNRyRn7SrkmmI5Fb/2URoyxxV+vnGpQdUhvD/SN8+IMP [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string E2 {
            get {
                return ResourceManager.GetString("E2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Evaluate {
            get {
                object obj = ResourceManager.GetObject("Evaluate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Evaluate1 {
            get {
                object obj = ResourceManager.GetObject("Evaluate1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Generate {
            get {
                object obj = ResourceManager.GetObject("Generate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Generate1 {
            get {
                object obj = ResourceManager.GetObject("Generate1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GridStreets {
            get {
                object obj = ResourceManager.GetObject("GridStreets", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Houses {
            get {
                object obj = ResourceManager.GetObject("Houses", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Houses1 {
            get {
                object obj = ResourceManager.GetObject("Houses1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LamellaHouses {
            get {
                object obj = ResourceManager.GetObject("LamellaHouses", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lamellas {
            get {
                object obj = ResourceManager.GetObject("lamellas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MassBalance {
            get {
                object obj = ResourceManager.GetObject("MassBalance", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MFH {
            get {
                object obj = ResourceManager.GetObject("MFH", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NumberOfHouses {
            get {
                object obj = ResourceManager.GetObject("NumberOfHouses", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap oCellStreet {
            get {
                object obj = ResourceManager.GetObject("oCellStreet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ParkingLot {
            get {
                object obj = ResourceManager.GetObject("ParkingLot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pLineBound {
            get {
                object obj = ResourceManager.GetObject("pLineBound", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Plot2D {
            get {
                object obj = ResourceManager.GetObject("Plot2D", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Plot2d1 {
            get {
                object obj = ResourceManager.GetObject("Plot2d1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap QuarterHouses {
            get {
                object obj = ResourceManager.GetObject("QuarterHouses", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RadiualStreets {
            get {
                object obj = ResourceManager.GetObject("RadiualStreets", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RandomHouses {
            get {
                object obj = ResourceManager.GetObject("RandomHouses", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SFH {
            get {
                object obj = ResourceManager.GetObject("SFH", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Site {
            get {
                object obj = ResourceManager.GetObject("Site", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SnapToStreet {
            get {
                object obj = ResourceManager.GetObject("SnapToStreet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SnapToTopo {
            get {
                object obj = ResourceManager.GetObject("SnapToTopo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Timer {
            get {
                object obj = ResourceManager.GetObject("Timer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
